import { useEffect } from 'react';
import { profile, projects, type Project as ProjectType } from '../data';
import { Plus, Spark } from '../components/Chrome';
import { OrbitArt, PrismArt, RetrievalArt, TrafficArt } from '../components/ProjectArt';
import SignalCanvas from '../components/SignalCanvas';

export default function ProjectPage({ project }: { project: ProjectType }) {
  useEffect(() => { document.title = `${project.name} — ${profile.name}`; }, [project.name]);
  const featured = projects.filter(item => item.kind !== 'concept');
  const next = featured[(featured.indexOf(project) + 1) % featured.length];
  return <main id="main" className={`project-page project-${project.slug} ${project.color}`}><section className="case-intro"><div className="case-top"><a href="/#work">Back to the work</a><span className="mono">PROJECT {project.number} / {project.kind === 'concept' ? 'FICTIONAL CONCEPT' : project.kind === 'portfolio' ? 'WORKING EXPERIENCE' : project.live ? 'LIVE APPLICATION' : project.slug === 'experiments' ? 'ONGOING EXPLORATION' : 'PROJECT'}</span></div><span className="eyebrow">{project.category}</span><h1>{project.name}<span>.</span></h1><div className="case-heading"><h2>{project.headline}</h2><p>{project.description}</p></div><div className="case-links">{project.live && <a className="pill-button dark" href={project.live} target="_blank" rel="noreferrer">Open live application <Plus /></a>}{project.github && <a href={project.github}>View source</a>}<a className="pill-button outline" href="#case-study">Explore the thinking <Plus /></a></div></section><section className="case-art" aria-label={`${project.name} interactive preview`}>{project.slug === 'rag' ? <RetrievalArt interactive /> : project.slug === 'anpr' ? <TrafficArt interactive /> : project.slug === 'orbit' ? <OrbitArt interactive /> : ['prism', 'experiments'].includes(project.slug) ? <PrismArt interactive /> : <div className="portfolio-art"><SignalCanvas /><span className="mono">ORIGINAL GENERATIVE GEOMETRY / DRAWN LIVE</span></div>}<p className="case-art-caption">{project.kind === 'concept' ? 'Original concept preview. Interact with the controls to explore it.' : project.slug === 'rag' ? 'Illustrative retrieval flow. Use “Next step” to explore the idea; open the live app for the actual implementation.' : project.slug === 'anpr' ? 'Simulated detection and tracking frames. Use “Next frame” to explore the visualization; this is not footage from the actual system.' : project.slug === 'experiments' ? 'Illustrative chart data. Change the time range to explore the interaction, or visit the playground for more working experiments.' : 'Live Canvas geometry. Move your pointer to change its perspective.'}</p></section><section className="case-story" id="case-study"><div className="case-sidebar"><span className="eyebrow">THE THINKING</span><h2>From question<br />to possibility.</h2><div className="project-tags">{project.technologies.map(tech => <span key={tech}>{tech}</span>)}</div></div><div className="case-story-content">{[['01 / THE PROBLEM', project.problem], ['02 / THE APPROACH', project.solution], ['03 / CONTRIBUTION', project.contribution], ['04 / WHAT EXISTS TODAY', project.result]].map(([title, text]) => <div key={title}><h3 className="mono">{title}</h3><p>{text}</p></div>)}</div></section><section className="next-project"><span className="eyebrow">ONE IDEA LEADS TO ANOTHER</span><a href={`/work/${next.slug}/`}><span>{next.name}</span><Spark /></a><a href="/#contact" className="text-button">Have something in mind? Let’s connect.</a></section></main>;
}
