import { useState } from 'react';
import { Spark } from './Chrome';

export function RetrievalArt({ interactive = false }: { interactive?: boolean }) {
  const [step, setStep] = useState(0);
  return <div className={`retrieval-art step-${step}`}>
    <div className="rag-window"><div className="window-bar"><span className="window-dots">● ● ●</span><span>RAG / PDF retrieval preview</span><span>✳</span></div><div className="rag-question"><span className="rag-avatar">A</span><p>How do you find a better answer?</p></div><div className="retrieval-diagram" aria-label="Illustrative flow: source documents are retrieved, then used as context for an answer"><div className="source-stack"><div>DOCUMENT 01 <span>≡</span></div><div>DOCUMENT 02 <span>≡</span></div><div>DOCUMENT 03 <span>≡</span></div></div><svg viewBox="0 0 120 110" aria-hidden="true"><path d="M0 20C60 20 30 55 100 55M0 55h100M0 90C60 90 30 55 100 55" fill="none" stroke="currentColor" strokeWidth="1.5" /><circle cx="100" cy="55" r="4" fill="currentColor" /></svg><div className="context-node"><Spark /><span>CONTEXT</span></div></div><div className="rag-answer"><span className="mini-spark">✳</span><p>{['First, find the right context.', 'Retrieve relevant source material.', 'Give the model the retrieved context.', 'Generate an answer grounded in that context.'][step]}</p></div><div className="rag-art-footer"><span>RETRIEVE. AUGMENT. GENERATE.</span>{interactive ? <button onClick={() => setStep(s => (s + 1) % 4)}>Next step <span aria-hidden="true">+</span></button> : <span>ILLUSTRATIVE PREVIEW</span>}</div></div>
    <span className="art-sticker mono">BETTER INPUT.<br />BETTER OUTPUT.</span>
  </div>;
}
export function OrbitArt({ interactive = false }: { interactive?: boolean }) {
  const [done, setDone] = useState<number[]>([0]);
  const tasks = ['Explore the possibilities', 'Make something tangible', 'Sweat the small details'];
  return <div className="orbit-art"><div className="orbit-orb" aria-hidden="true"><div /><div /><div /></div><div className="orbit-window"><div className="window-bar"><span className="orbit-logo">o<span>orbit</span></span><span>YOUR SPACE, IN SYNC</span></div><div className="orbit-heading"><span className="mono">MONDAY / A FRESH START</span><h3>A little clarity.</h3><span className="orbit-counter">{done.length} / 3 complete</span></div><div className="task-list">{tasks.map((task, i) => <button key={task} type="button" aria-pressed={done.includes(i)} disabled={!interactive} onClick={() => setDone(d => d.includes(i) ? d.filter(v => v !== i) : [...d, i])}><span className={`task-checkbox ${done.includes(i) ? 'checked' : ''}`}>{done.includes(i) ? '✓' : ''}</span><span>{task}</span><span className="task-tag">{['IDEATE', 'BUILD', 'POLISH'][i]}</span></button>)}</div><div className="orbit-bottom"><div className="avatar-stack"><span>A</span><span>M</span><span>J</span></div><span>Good things happen together.</span><Spark /></div></div></div>;
}
const datasets = { '7 days': [28, 44, 38, 67, 55, 78, 92], '30 days': [40, 30, 55, 42, 75, 69, 88], '90 days': [18, 27, 41, 35, 58, 74, 96] };
export function PrismArt({ interactive = false }: { interactive?: boolean }) {
  const [range, setRange] = useState<keyof typeof datasets>('7 days');
  const points = datasets[range].map((v, i) => `${25 + i * 48},${160 - v * 1.3}`).join(' ');
  return <div className="prism-art"><div className="prism-window"><div className="window-bar"><span className="prism-logo">▰ prism</span><span>ILLUSTRATIVE DATA</span></div><div className="prism-heading"><span className="mono">THE BIG PICTURE</span><h3>Looking up.</h3><div className="chart-ranges" aria-label="Chart time range">{Object.keys(datasets).map(key => <button key={key} disabled={!interactive} aria-pressed={range === key} onClick={() => setRange(key as keyof typeof datasets)}>{key}</button>)}</div></div><div className="chart"><svg viewBox="0 0 340 185" role="img" aria-label={`Illustrative trend over ${range}: ${datasets[range].join(', ')}`}><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c6ea58" stopOpacity=".4" /><stop offset="100%" stopColor="#c6ea58" stopOpacity="0" /></linearGradient></defs>{[40, 80, 120, 160].map(y => <line key={y} x1="20" y1={y} x2="320" y2={y} stroke="#ffffff15" />)}<polygon points={`25,170 ${points} 313,170`} fill="url(#chart-fill)" /><polyline points={points} fill="none" stroke="#d5f45b" strokeWidth="3" strokeLinejoin="round" />{datasets[range].map((v, i) => <circle key={i} cx={25 + i * 48} cy={160 - v * 1.3} r="4" fill="#d5f45b" />)}</svg></div><div className="prism-bottom"><span>LESS NOISE.</span><span>MORE PERSPECTIVE.</span></div></div><span className="prism-orbit" aria-hidden="true">✳</span></div>;
}

export function TrafficArt({ interactive = false }: { interactive?: boolean }) {
  const [frame, setFrame] = useState(0);
  const vehicles = [
    { x: 97, y: 34 + frame * 13, label: 'DEMO 01', color: '#b6a0ff' },
    { x: 215, y: 115 - frame * 11, label: 'DEMO 02', color: '#ff6333' },
    { x: 101, y: 207 - frame * 12, label: 'DEMO 03', color: '#f4f1ea' },
  ];
  return <div className="traffic-art"><div className="traffic-window"><div className="window-bar"><span className="mono">VISION / PIPELINE PREVIEW</span><span>SIMULATED FRAME</span></div><svg className="traffic-diagram" viewBox="0 0 380 320" role="img" aria-label={`Simulated traffic frame ${frame + 1}: three illustrative vehicles with detection boxes and example plate labels`}><rect x="57" y="0" width="270" height="320" fill="#2c3031" /><path d="M69 0v320M316 0v320" stroke="#77807a" strokeWidth="2" /><path d="M192 0v320" stroke="#b3b8ae" strokeDasharray="19 18" strokeWidth="2" />{vehicles.map(vehicle => <g key={vehicle.label} transform={`translate(${vehicle.x} ${vehicle.y})`}><rect x="7" y="8" width="43" height="69" rx="9" fill={vehicle.color} /><rect x="12" y="19" width="33" height="17" rx="3" fill="#101112" opacity=".75" /><rect x="12" y="52" width="33" height="11" rx="2" fill="#101112" opacity=".45" /><path d="M-1 14V0h16M43 0h16v14M59 70v16H43M15 86H-1V70" fill="none" stroke="#d5f45b" strokeWidth="2" /><rect x="-2" y="-19" width="65" height="15" fill="#d5f45b" /><text x="3" y="-8" fill="#101112" fontSize="8" fontFamily="monospace">{vehicle.label}</text></g>)}<text x="346" y="28" fill="#acb5ad" fontSize="8" fontFamily="monospace" transform="rotate(90 346 28)">DETECT / TRACK / READ PLATE</text></svg><div className="traffic-art-footer"><span className="mono">FRAME 00{frame + 1} / ILLUSTRATIVE</span>{interactive ? <button onClick={() => setFrame(value => (value + 1) % 4)}>Next frame <span aria-hidden="true">+</span></button> : <span className="mono">YOLO + OCR</span>}</div></div></div>;
}
