export interface Profile { name: string; shortName: string; role: string; statement: string; interests: string[]; availability: string; experience: string; education: { qualification: string; institution: string; detail: string }[]; email?: string; phone?: string; github?: string; linkedin?: string; resume?: string }
export interface Project { slug: string; number: string; name: string; category: string; kind: 'real' | 'concept' | 'portfolio'; color: string; headline: string; description: string; problem: string; solution: string; technologies: string[]; contribution: string; live?: string; github?: string; result: string }
export interface Experiment { id: 'signal' | 'spring' | 'circuit'; title: string; description: string }
export type Discovery = 'pulse' | 'spring' | 'circuit';
export const profile: Profile = {
  name: 'Aditya Mishra', shortName: 'Aditya', role: 'AI Engineer & Full-Stack Developer',
  statement: 'I build intelligent, modern, user-centric products. My work brings together frontend development, machine learning, computer vision, and Generative AI to turn complex ideas into practical applications.',
  interests: ['Boxing', 'Fitness', 'Exploring new technologies'],
  availability: 'Open to AI/ML internships, full-time opportunities, freelance projects, and collaborations in AI, software development, and intelligent automation.',
  experience: 'Software engineering experience across web development, AI/ML applications, computer vision, and Generative AI.',
  education: [
    { qualification: 'M.Sc. Industrial AI', institution: 'Albstadt-Sigmaringen University, Germany', detail: 'Currently pursuing advanced studies in AI, data science, industrial systems, and intelligent automation.' },
    { qualification: 'B.Tech. Computer Science & Engineering', institution: 'Bharati Vidyapeeth College of Engineering', detail: 'CGPA: 9.22 / 10' },
  ],
  email: 'adityamishra3917@gmail.com', phone: '+49 1745977418', github: 'https://github.com/Aditya007-source',
  // Add LinkedIn, a résumé, and project repository URLs when available.
};
export const projects: Project[] = [
  { slug: 'rag', number: '01', name: 'RAG Intelligent PDF Reader', category: 'GENERATIVE AI / DOCUMENT INTELLIGENCE', kind: 'real', color: 'orange', headline: 'Your documents. A conversation away.', description: 'An AI-powered document assistant that lets you upload PDFs and ask natural-language questions about their content.', problem: 'Finding an answer inside a long PDF should not require manually searching through every page. Generic model knowledge is not enough when the answer depends on a particular document.', solution: 'Process the PDF, split its text into chunks, create vector embeddings, and index them with FAISS. Retrieve relevant passages semantically, then use LangChain and the Gemini API to generate an answer with that context.', technologies: ['Python', 'LangChain', 'FAISS', 'Gemini API', 'RAG', 'Vector Embeddings'], contribution: 'Designed and developed the RAG pipeline: document processing, text chunking, vector indexing, semantic retrieval, and AI-powered question answering.', live: 'https://aditya-rag-online.streamlit.app/', result: 'A deployed document assistant for PDF uploads and natural-language questions. The diagram below is an illustrative pipeline preview; use the live application to try the document workflow.' },
  { slug: 'anpr', number: '02', name: 'ANPR & Traffic Monitoring', category: 'COMPUTER VISION / REAL-TIME VIDEO', kind: 'real', color: 'lavender', headline: 'Turn traffic into something you can understand.', description: 'An Automatic Number Plate Recognition and traffic analysis system built with computer vision and deep learning.', problem: 'Traffic video contains useful information about vehicles and their movement, but extracting it manually is slow and difficult to scale.', solution: 'Combine YOLO vehicle detection, OpenCV video processing, vehicle tracking, and OCR to recognize number plates and analyze traffic in a real-time processing workflow.', technologies: ['YOLO', 'OpenCV', 'OCR', 'Vehicle Tracking', 'Deep Learning'], contribution: 'Developed an AI-based ANPR and traffic analysis system, working on detection, number plate recognition, tracking, and real-time video processing.', result: 'A computer vision project focused on vehicle and number plate analysis. The preview uses simulated frames to explain the pipeline; it is not recorded output from the actual system.' },
  { slug: 'experiments', number: '03', name: 'Web & AI Experiments', category: 'FULL-STACK DEVELOPMENT / ONGOING EXPLORATION', kind: 'real', color: 'lime', headline: 'Small experiments. Useful possibilities.', description: 'Responsive web interfaces and ongoing experiments in Generative AI, computer vision, machine learning, automation, and data-driven applications.', problem: 'A technical idea becomes useful when people can interact with it clearly, reliably, and comfortably across devices.', solution: 'Build reusable frontend components and practical prototypes, with attention to performance, usability, and clear interfaces. Keep exploring how AI and automation can support the experience.', technologies: ['Frontend Development', 'Generative AI', 'Computer Vision', 'Machine Learning', 'Automation'], contribution: 'Built responsive, reusable web components and interfaces, while continuing to experiment with AI and data-driven applications.', result: 'An ongoing body of development and experimentation. The interactive chart below is an illustrative portfolio demonstration; the playground contains additional working interface experiments.' },
  { slug: 'portfolio', number: '04', name: 'Signal / Play', category: 'CREATIVE DEVELOPMENT / THE SITE ITSELF', kind: 'portfolio', color: 'cream', headline: 'The medium is part of the message.', description: 'An interactive portfolio that makes a little room for curiosity.', problem: 'A portfolio with a small project collection still needs to demonstrate engineering and design decisions.', solution: 'Original generative graphics, native scrolling, accessible experiments, and prerendered pages make the experience itself a working sample.', technologies: ['React', 'TypeScript', 'Canvas', 'Motion', 'Vite'], contribution: 'The complete experience: original artwork algorithms, components, responsive layouts, local discovery state, and interaction design.', result: 'Explore the working site and its lab. Performance and accessibility are checked during development; no award or commercial impact is claimed.' },
  { slug: 'orbit', number: '05', name: 'Orbit', category: 'PRODUCT DESIGN / INTERACTIVE CONCEPT', kind: 'concept', color: 'lavender', headline: 'A little less chaos. A lot more orbit.', description: 'An imagined workspace for teams who like their plans clear and their days a little calmer.', problem: 'Project plans often scatter across calendars, messages, and disconnected task lists.', solution: 'A proposed workspace that groups tasks around a focused daily plan. This concept explores approachable interaction and visual hierarchy.', technologies: ['React', 'TypeScript', 'Interaction design'], contribution: 'Original fictional concept, interface design, and interactive task preview built for this portfolio.', result: 'An interactive prototype, not a shipped client product. No commercial results are claimed.' },
  { slug: 'prism', number: '06', name: 'Prism', category: 'DATA VISUALIZATION / INTERACTIVE CONCEPT', kind: 'concept', color: 'lime', headline: 'See the signal. Skip the noise.', description: 'An imagined analytics tool that gives data a clearer point of view.', problem: 'Dashboards can show a lot of numbers without helping people understand their relationships.', solution: 'A proposed analytics interface that emphasizes one trend at a time, with directly adjustable views.', technologies: ['React', 'SVG', 'Data visualization'], contribution: 'Original fictional concept and working chart-range interaction built for this portfolio.', result: 'A local visualization prototype with illustrative data. No real customer or revenue figures are used.' },
];
export const experiments: Experiment[] = [
  { id: 'signal', title: 'Make some waves', description: 'Move across the field, or send a pulse. A small input, a surprisingly big ripple.' },
  { id: 'spring', title: 'Feel the physics', description: 'Pull the object and let go. Tune the spring to find your favorite kind of bounce.' },
  { id: 'circuit', title: 'Close the loop', description: 'Rotate each tile until the four corners form a connected circuit. No timer. Just curiosity.' },
];
